---
title: "NOAA data"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(plotly)
```

```{r load NOAA data}
library(p8105.datasets)
ny_noaa_raw_data = p8105.datasets::ny_noaa %>% 
  janitor::clean_names()
```
```{r Clean NOAA data}
ny_noaa_clean_data = 
ny_noaa_raw_data %>%
  mutate(year =  as.numeric(format(as.Date(ny_noaa_raw_data$date, format = "%d/%m/%Y"), "%Y")),   #reformat year month and day
         month =  as.numeric(format(as.Date(ny_noaa_raw_data$date, format = "%d/%m/%Y"), "%m")),
         day  =  as.numeric(format(as.Date(ny_noaa_raw_data$date, format = "%d/%m/%Y"), "%d")), 
         tmax =  as.numeric(tmax)/10,  #reformat and adjust valye of perciptation and min/max temp
         tmin =  as.numeric(tmin)/10,
         prcp =  prcp/10, 
         month = as.numeric(month)
         ) %>% 
        select(-date)
#head(ny_noaa_clean_data)
```


```{r plot}
# scatter plot 

# ny_noaa_clean_data %>% 
#   group_by(year, month) %>% 
#   summarise(total_prcp = sum(prcp, na.rm = TRUE)) %>% 
#   plot_ly(x = ~year , y = ~total_prcp, type = "scatter", mode = "markers")
```




Column {data-width=650}
-----------------------------------------------------------------------

### Average Snow Fall per Month (1981~2010)

```{r chart 1}
# snowed per month // bar plot
ny_noaa_clean_data %>% 
  filter(!is.na(snow)) %>% 
  group_by(month) %>% 
  summarise(avg_snowfall = mean(snow)) %>%
  plot_ly(x = ~month, y = ~avg_snowfall, type = "bar") %>% 
  layout(title = "Average Snow Fall per Month (1981~2010)" , 
         yaxis = list(title = "Average monthly snow fall (mm)"), 
         xaxis = list(title = "Month"))

```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r box plot}
# box plot
ny_noaa_clean_data %>% 
  filter(year >= 2000) %>% 
  group_by(year, month) %>% 
  summarise(total_prcp = sum(prcp, na.rm = TRUE)) %>% 
  plot_ly(x = ~year , y = ~total_prcp, type = "box") %>% 
  layout(title = "ditribution of yearly Precipitation (2000~2010)" , 
       yaxis = list(title = "Precipitation (mm)"), 
       xaxis = list(title = "Year"))  
 ```

### Chart C

```{r scatter plot }
# scatter plot 
ny_noaa_clean_data %>% 
  filter(!is.na(tmax) & !is.na(tmin) & year == 2000) %>% 
  group_by(month) %>% 
  mutate(monthly_avg = mean(tmax)) %>% 
  plot_ly(y = ~monthly_avg, x = ~month ,
          type = "scatter", 
          mode = 'line') %>% 
  layout(title = "Max temperature in year 2000" , 
         yaxis = list(title = "Temp (ºC)"), 
         xaxis = list(title = "Month")
         )  
  
```



